### ISSUE TITLE
Merge with original project?

### ISSUE THREAD

**Issue by marcosmko** [igortavtib/robotframework-appiumflutterlibrary#12]
Hello all!

Just wondering here, is it possible to merge this project with the original one?
It would be great if we could use the same library for flutter and native.

**Comment by igortavtib** [comment]
Hello!

 My first plan was to contribute to the original project to enable de possibility to test flutter apps with AppiumLibrary.

 When I starded coding I noticed that I would have to make significantly changes at the project structure to use Flutter Driver, so it wouldn't be worth.
