### ISSUE TITLE
Swipe right and left

### ISSUE THREAD

**Issue by zied-eb** [igortavtib/robotframework-appiumflutterlibrary#13]
Hi,

Thanks for the library, it made it possible to automate our flutter app tests !
We managed to convert our tests to the Flutter driver almost fine.

Only thing remaining so far is the swipe feature, especially horizontally.
Unfortunately, scroll keywords cannot help. As we want to swipe left and right.

Any thoughts, workarounds ?

**Comment by igortavtib** [comment]
Hey, thanks for the feedback!

 I'm planning to create the swipe keyword since beta 1. Flutter Driver seems to not support WebDriver.swipe(), so I have to find another way.
 I will work on this issue this week and hope I can release this keyword at beta 3.

**Comment by zied-eb** [comment]
Appreciated, that would be perfect !

Swipe actions are very critical for our app (and I believe for most of modern apps)

**Comment by zied-eb** [comment]
Looking forward for this feature.
