### ISSUE TITLE
No Capture Page Screenshot when failure

### ISSUE THREAD

**Issue by RodaxQA** [igortavtib/robotframework-appiumflutterlibrary#15]
Hi,

There is no "Capture Page Screenshot" taken by default when a keyword is FAIL.

```
Failed test case
    Open Application 	http://localhost:4723/wd/hub 	automationName=flutter    platformName=Android    platformVersion=10    deviceName=device    appPackage=dev.flutter.formApp.form_app    appActivity=dev.flutter.formApp.form_app.MainActivity
    Set Log Level    TRACE
    Run Keyword And Continue On Failure    Wait For Element    blabla    15
    Run Keyword And Continue On Failure    Element Should Be Visible    blabla
    Run Keyword And Continue On Failure    Click Element    blabla
    [Teardown]    Close All Applications
```

Here is my log.html file : https://optimistic-brattain-abf395.netlify.app/ 
Don't forget to put report log level to "TRACE" on html page

( I see also test hangs for 2 minutes when a locator is not found for "Click Element". 
I think it's related to this issue on appium-flutter-driver side : https://github.com/appium-userland/appium-flutter-driver/issues/181 )

**Comment by igortavtib** [comment]
Version 1.0.0 released with this fix.

I'm closing this issue.
