### ISSUE TITLE
Key locator usage

### ISSUE THREAD

**Issue by yahyakara** [igortavtib/robotframework-appiumflutterlibrary#18]
Hi, First of all thank for this project,
I am new on RobotFrameWork usage, I can't find that how can ı define key locator on keywords by this library 
Could you please share test example about key locator.

I tried these syntax  : 

- Click Element       key=skip_button  
- Wait For Element   key=skip_button        10s

Thanks for support in advance

**Comment by igortavtib** [comment]
Since key locator is the default locator you can use this syntax:

- Click Element skip_button
- Wait Element skip_button 10s

But it should work using the syntax you're using too. If it isnt't it's probably a bug.

**Comment by paimvictor** [comment]
Hey there! Closing this issue since we dont have any updates on that. If you have any other question, i am glad to help!
