### ISSUE TITLE
Encountered internal error running command: Error: input is invalid

### ISSUE THREAD

**Issue by yahyakara** [igortavtib/robotframework-appiumflutterlibrary#19]
Hi 
When I started the test, the app is running and driver returns error that input error on following keyword.  Altough I tried Wait For Element and absent option the driver doesnt wait the element and it returns input error immediately (I use default timeout but I tried with setting it manually).  

*** Keywords ***
Click skip button on onboard
    [Documentation]    Skip onboard Screen
    Wait For Element Absent     ${SkipButton}

Test Teardown  End The test applications

*** Test Cases ***
Onboard Screen test demo - desc
  Open Android Test App
  Click skip button on onboard

Onboard Screen test title - desc                                      | FAIL |
Element 'skip_button' still not absent in 20 seconds

`[HTTP] --> POST /session/e8346d4b-a7cd-44fe-b32d-2704cc6b4921/execute/sync
[HTTP] {"script":"flutter:waitForAbsent","args":[{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoic2tpcF9idXR0b24iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},20]}
[debug] [FlutterDriver@5bda (e8346d4b)] Calling AppiumDriver.execute() with args: ["flutter:waitForAbsent",[{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoic2tpcF9idXR0b24iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},20],"e8346d4b-a7cd-44fe-b32d-2704cc6b4921"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@5bda (e8346d4b)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoic2tpcF9idXR0b24iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="}
[debug] [FlutterDriver@5bda (e8346d4b)]     at decode (/Users/yahya.kara/.appium/node_modules/finder/nodejs/lib/base64url.ts:15:11)
[debug] [FlutterDriver@5bda (e8346d4b)]     at deserialize (/Users/yahya.kara/.appium/node_modules/finder/nodejs/lib/deserializer.ts:4:20)
[debug] [FlutterDriver@5bda (e8346d4b)]     at FlutterDriver.executeElementCommand (/Users/yahya.kara/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:172:52)
[debug] [FlutterDriver@5bda (e8346d4b)]     at /Users/yahya.kara/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
[debug] [FlutterDriver@5bda (e8346d4b)]     at FlutterDriver.execute (/Users/yahya.kara/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:48:27)
[debug] [FlutterDriver@5bda (e8346d4b)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
[debug] [FlutterDriver@5bda (e8346d4b)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:154:12
[debug] [FlutterDriver@5bda (e8346d4b)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:287:31)
[debug] [FlutterDriver@5bda (e8346d4b)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:153:9)
[debug] [FlutterDriver@5bda (e8346d4b)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:3)
[debug] [FlutterDriver@5bda (e8346d4b)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:89:39)
[debug] [FlutterDriver@5bda (e8346d4b)]     at runMicrotasks (<anonymous>)
[debug] [FlutterDriver@5bda (e8346d4b)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [FlutterDriver@5bda (e8346d4b)]     at FlutterDriver.executeCommand (/Users/yahya.kara/.appium/node_modules/appium-flutter-driver/lib/driver.ts:139:16)
[debug] [FlutterDriver@5bda (e8346d4b)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:673:14)
[debug] [FlutterDriver@5bda (e8346d4b)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:763:16)
[debug] [FlutterDriver@5bda (e8346d4b)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:685:17)
[debug] [FlutterDriver@5bda (e8346d4b)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)`

I am using Appium 2.0 and robotframework-appiumflutterlibrary 1.0.0b2

Thank for your helps

**Comment by igortavtib** [comment]
Could you try to update to version 1.0.0?

This error is related to this issue: #11

It is suposed to be fixed at 1.0.0

**Comment by yahyakara** [comment]
Thank you Igor It works perfectly 
Regards
