### ISSUE TITLE
Help intergrate with robot Framework

### ISSUE THREAD

**Issue by edwardPham6868** [igortavtib/robotframework-appiumflutterlibrary#23]
Hi Igortavtib,

Could you make more detail about how Appium Flutter Driver working ? 
I already add :
At first, include flutter_driver package to your dev dependencies at pubspec.yaml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

Then go to your main.dart file and add enableFlutterDriverExtension() to your main function before runApp()

import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';

void main() {
  enableFlutterDriverExtension();
  runApp(const MyApp());
}

...

but I still couldn't start Flutter application and don't know how to get element location.
Please make a video demo for us understant how driver work.

Thank you!

**Comment by paimvictor** [comment]
Hey edward!

Im going to make a quickstart to ease the first steps. As soon as possible, i will push it!

**Comment by igortavtib** [comment]
This should be in our documentation, but is not.

After doing the first setup you must add the key value to the components you want to test. I have this example with a floatingActionButton:

```dart
 floatingActionButton: FloatingActionButton(
        // Here you set the key that will be used to find the element
        key: Key('increment-button'),
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
```

Now you can just use the key to interact with yout element on robot tests:

`Click Element    increment-button`

 At the keyword documentation you can find other locators you can use instead the key locator, as the text locator.

**Comment by edwardPham6868** [comment]
Thanks for your answer!
I still get this error, please help 

Status: Start application  -> show UI and close in second.
#---------------------------
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
Chay dau con sau                                                      | FAIL |
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

#--------------------------

**Comment by edwardPham6868** [comment]
I write very simple code for Flutter demo app, please help

#------------------------------------------------
*** Settings ***
Library    AppiumFlutterLibrary

*** Keywords ***
Open Demo Application
  Open Application   http://localhost:4723/wd/hub    platformName=Android    automationName=flutter    platformVersion=10    deviceName=emulator-5554    appPackage=com.example.flutter_automation    appActivity=MainActivity    

Close Application
    Close Application


*** Test Cases ***
Chay dau con sau
    Open Demo Application
    Click Element     increment
    Sleep    10s
    Click Element     increment
    Sleep    10s
    Close Application

**Comment by paimvictor** [comment]
Hey there!

Can u test using a key for the locator? 
Like this:
![image](https://user-images.githubusercontent.com/51713836/197781333-36358205-a5d4-44cd-b4fa-ed8c85562fad.png)

**Comment by edwardPham6868** [comment]
Do your code work without appPackage / appActivities ?
I still couldn't fix this

#--------------
[ WARN ] Keyword 'AppiumFlutterLibrary.Capture Page Screenshot' could not be run on failure: No application is open
Chay dau con sau                                                      | FAIL |
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

**Comment by paimvictor** [comment]
Yes, it does. This screenshot that i sent is running without any problems.

Try setting the app parameter, pointing to the location of the apk

**Comment by edwardPham6868** [comment]
I found problem => I am missing prefix of app activities
Should be like this: com.example.flutter_application_1.MainActivity
